- id: '1698693759878'
  alias: Forest - turn on lights on night fall
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: 518ca2a7f6303b6656a20cb2b725bb8a
    entity_id: bec7e3dbbe0214f07160cc79c41ec8ab
    domain: switch
  - wait_for_trigger:
    - platform: time
      at: 05:00:00
  - type: turn_off
    device_id: 518ca2a7f6303b6656a20cb2b725bb8a
    entity_id: bec7e3dbbe0214f07160cc79c41ec8ab
    domain: switch
  mode: single
- id: '1700426149941'
  alias: Entrence = turn lights on if doors opens
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.pagrindinis_iejimas_contact
    - binary_sensor.garazo_durys_contact
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - type: turn_on
    device_id: aa4117474f58eaea7eab3f43b258c1fe
    entity_id: bf0f2545c87b6a33c8062eec7a04d8e1
    domain: switch
  - wait_for_trigger: []
    timeout:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: aa4117474f58eaea7eab3f43b258c1fe
    entity_id: bf0f2545c87b6a33c8062eec7a04d8e1
    domain: switch
  mode: single
- id: '1711057566845'
  alias: Back home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lauko_vartai
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    after_offset: '2'
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.entrada
      - light.terrasse
      - light.shellypro4pm_34987a68f204_switch_3
      - light.shellypro4pm_34987a68f204_switch_0
      - light.shellyplus1_c82e180bd154_switch_0
      - light.shellypro4pm_34987a68f204_switch_1
  - wait_for_trigger: []
    timeout:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.entrada
      - light.terrasse
  mode: single
