button_card_templates: !include button_card_templates.yaml

views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      margin: 0
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .       .       ."
        "sidebar  svetaine  garazas  sovrum  ."
        "sidebar  media       kita  namai   ."
        "sidebar  footer      footer  footer  ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .        ."
            ".  sidebar     sidebar  ."
            ".  svetaine  sovrum   ."
            ".  garazas      kita   ."
            ".  media       namai    ."
            ".  footer      footer   ."
            ".  .           .        ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .       ."
            "sidebar  svetaine  sovrum  ."
            "sidebar  garazas      kita  ."
            "sidebar  media       namai   ."
            "sidebar  footer      footer  ."
            "sidebar  .           .       ."
    cards:

      - type: custom:button-card #extra_styles fix
        styles: {card: [display: none]}

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:

          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar

          - type: conditional
            conditions:
              - entity: input_boolean.laundry_display
                state: 'on'
            card:
              type: custom:button-card
              entity: timer.laundry
              hold_action:
                action: call-service
                service: input_boolean.turn_off
                service_data:
                  entity_id: input_boolean.laundry_display
              template: laundry

      #################################################
      #                                               #
      #                  Svetainė                     #
      #                                               #
      #################################################
      - type: grid
        title: Svetainė
        view_layout:
          grid-area: svetaine
        columns: 1
        cards:
          - type: custom:swipe-card
            parameters:
              speed: 550
              spaceBetween: 40
              threshold: 5
            cards:

              - type: grid
                columns: 2
                cards:
            
                
                  - type: custom:button-card
                    entity: light.group_belysning
                    name: Virtuvė
                    template:
                      - light
                      - icon_hue

                  - type: custom:button-card
                    entity: light.horna
                    name: Valgomasis
                    template:
                      - light
                      - icon_hue

                  - type: custom:button-card
                    entity: light.horna
                    name: Svetainė
                    template:
                      - light
                      - icon_hue

                  - type: custom:button-card
                    entity: media_player.sony_bravia_tv
                    name: Tv
                    state_display: >
                      [[[
                        if (variables.state === 'playing') {
                          return 'På';
                        }
                        if (variables.state === true) {
                          return variables.translate_unknown;
                        }
                      ]]]
                    hold_action:
                      !include popup/svetaine_tv.yaml
                    template:
                      - base
                      - icon_tv
                      - loader
              - type: grid
                columns: 2
                cards:

                  - type: custom:button-card
                    entity: light.horna
                    name: Vasaros sodas
                    template:
                      - light
                      - icon_hue

      #################################################
      #                                               #
      #                    Garažas                    #
      #                                               #
      #################################################

      - type: grid
        title: Garažas/Laukas
        view_layout:
          grid-area: garazas
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.dator
            name: Vartai
            template:
              - light
              - icon_spot

          - type: custom:button-card
            entity: light.group_taklampor
            name: Lauko vartai
            template:
              - light
              - icon_spot
              
          - type: custom:button-card
            entity: light.terrasse
            name: Terasa
            template:
              - light
              - icon_spot
              
          - type: custom:button-card
            entity: light.forest_side
            name: Miško pusė
            template:
              - light
              - icon_spot

      #################################################
      #                                               #
      #                    SOVRUM                     #
      #                                               #
      #################################################

      - type: grid
        title: Miegamasis 1.
        view_layout:
          grid-area: sovrum
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.group_sanglampor
            name: Sänglampor
            template:
              - light
              - icon_lamp

          - type: custom:button-card
            entity: climate.ac
            name: Klimat
            hold_action:
              !include popup/sovrum_klimat.yaml
            template:
              - base
              - icon_climate
              - climate
            variables:
              circle_input: >
                [[[
                  if (entity) {
                    return entity.state === 'cool' ?
                      entity.attributes.temperature :
                      entity.attributes.current_temperature;
                  }
                ]]]

          - type: custom:button-card
            entity: switch.playstation_5
            name: Playstation
            hold_action:
              !include popup/svetaine_playstation.yaml
            template:
              - base
              - icon_ps5
              - loader

          - type: custom:button-card
            entity: media_player.samsung_tv
            name: "Tv\u00B2"
            hold_action:
              !include popup/sovrum_tv2.yaml
            template:
              - base
              - icon_tv
              - loader

      #################################################
      #                                               #
      #                     MEDIA                     #
      #                                               #
      #################################################

      - type: grid
        title: Media
        view_layout:
          grid-area: media
        columns: 1
        cards:

          - type: custom:swipe-card
            parameters:
              speed: 550
              spaceBetween: 40
              threshold: 5
            cards:

              - type: horizontal-stack
                cards:

                  - type: conditional
                    conditions:
                      - entity: select.conditional_media
                        state_not: svetaine

                      - entity: select.conditional_media
                        state_not: Sovrum

                      - entity: select.conditional_media
                        state_not: Spotify

                      - entity: select.conditional_media
                        state_not: Kök
                    card:
                      type: custom:button-card
                      entity: sensor.plex_recently_added
                      name: Senast tillagt
                      tap_action:
                        action: none
                      template:
                        - conditional_media
                        - icon_plex

                  - type: conditional
                    conditions:
                      - entity: select.conditional_media
                        state: svetaine
                    card:
                      type: custom:button-card
                      entity: media_player.svetaine
                      template:
                        - conditional_media
                        - icon_apple_tv

                  - type: conditional
                    conditions:
                      - entity: select.conditional_media
                        state: Sovrum
                    card:
                      type: custom:button-card
                      entity: media_player.sovrum
                      template:
                        - conditional_media
                        - icon_apple_tv

                  - type: conditional
                    conditions:
                      - entity: select.conditional_media
                        state: Spotify
                    card:
                      type: custom:button-card
                      entity: media_player.spotify
                      template:
                        - conditional_media
                        - icon_spotify

                  - type: conditional
                    conditions:
                      - entity: select.conditional_media
                        state: Kök
                    card:
                      type: custom:button-card
                      entity: media_player.kok
                      template:
                        - conditional_media
                        - icon_nest_mini

              - type: grid
                columns: 2
                cards:

                  - type: custom:button-card
                    entity: media_player.svetaine
                    name: svetaine
                    template:
                      - media
                      - icon_apple_tv

                  - type: custom:button-card
                    entity: media_player.sovrum
                    name: Sovrum
                    template:
                      - media
                      - icon_apple_tv

                  - type: custom:button-card
                    entity: media_player.spotify
                    name: Spotify
                    template:
                      - media
                      - icon_spotify

                  - type: custom:button-card
                    entity: media_player.kok
                    name: Nest Mini
                    template:
                      - media
                      - icon_nest_mini

      #################################################
      #                                               #
      #                    KITA                       #
      #                                               #
      #################################################

      - type: grid
        title: Kita
        view_layout:
          grid-area: kita
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.terrasse
            name: Koridorius
            template:
              - light
              - icon_spot
              
          - type: custom:button-card
            entity: light.forest_side
            name: Laiptai
            template:
              - light
              - icon_spot
              
          - type: custom:button-card
            entity: light.forest_side
            name: Katilinė
            template:
              - light
              - icon_spot

          - type: custom:button-card
            entity: switch.gosund_fan_switch
            name: 
            hold_action:
              !include popup/garazas_flakt.yaml
            template:
              - base
              - icon_fan2
              - loader

      #################################################
      #                                               #
      #                     NAMAI                     #
      #                                               #
      #################################################

      - type: grid
        title: Namai
        view_layout:
          grid-area: namai
        columns: 2
        cards:

          - type: custom:button-card
            entity: person.jonas
            name: Jonas
            triggers_update:
              - sensor.jonas_iphone_last_update_trigger
            tap_action:
              !include popup/home_jonas.yaml
            variables:
              retain: sensor.jonas_iphone_last_update_trigger
            template: person

          - type: custom:button-card
            entity: person.sanja
            name: Sanja
            triggers_update:
              - sensor.sanja_last_changed
            tap_action:
              !include popup/hemma_sanja.yaml
            variables:
              retain: sensor.sanja_last_changed
            template: person

          - type: custom:button-card
            entity: script.home_leave
            name: Stäng allt
            hold_action:
              action: none
            template:
              - base
              - icon_away

          - type: custom:button-card
            entity: script.home_arrive
            name: Namai
            hold_action:
              action: none
            template:
              - base
              - icon_home

      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      - type: horizontal-stack
        view_layout:
          grid-area: footer
        cards:

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:nas"></ha-icon> NAS
            tap_action:
              !include popup/footer/nas.yaml
            variables:
              notify: >
                [[[
                  let status = states['sensor.nas_volume_1_status'],
                    security = states['binary_sensor.nas_security_status'],
                    disk_use = states['sensor.disk_use_percent'],
                    nas_update = states['binary_sensor.nas_update_available'];
                  if (status && security && disk_use && nas_update) {
                    return nas_update.state === 'on'
                      ? 1
                      : status.state === 'background_scrubbing' ||
                        security.state === 'on' ||
                        parseFloat(disk_use.state) >= 85;
                  }
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:arrow-up-bold-circle-outline"></ha-icon> Uppdatera
            tap_action:
              !include popup/footer/updater.yaml
            variables:
              notify: >
                [[[
                  let hass_installed = hass.config.version,
                    hass_version_latest = states['sensor.hass_version_latest'],
                    hass_version_latest_beta = states['sensor.hass_version_latest_beta'],
                    hacs = states['sensor.hacs'];

                  if (hass_version_latest && hass_version_latest.state.includes('.')
                    && hass_version_latest_beta && hass_version_latest_beta.state.includes('.')
                    && hacs && Number.isInteger(parseInt(hacs.state))) {

                    let hass_latest = hass_installed.includes('b')
                        ? hass_version_latest_beta.state
                        : hass_version_latest.state,
                      hass_count = hass_installed !== hass_latest ? 1 : 0;
                    return hass_count + parseInt(hacs.state);
                  }
                  return 0;
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:robot-vacuum-variant"></ha-icon> Städa
            tap_action:
              !include popup/footer/vacuum.yaml
            variables:
              notify: >
                [[[
                  let last_clean = states['sensor.morty_last_clean_end'],
                    week_ms = 6048e5;
                  if (last_clean) {
                    return (Date.now() - Date.parse(last_clean.state)) > week_ms;
                  }
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:chart-line-variant"></ha-icon> Historik
            tap_action:
              !include popup/footer/history.yaml
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:tablet"></ha-icon> Platta
            tap_action:
              !include popup/footer/tablet.yaml
            variables:
              notify: >
                [[[
                  let plugged_in = states['binary_sensor.galaxy_tab_a_plugged_in'];
                  if (plugged_in) {
                    return plugged_in.state === 'off';
                  }
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:router-wireless"></ha-icon> Router
            tap_action:
              !include popup/footer/router.yaml
            variables:
              notify: >
                [[[
                  let internet = states['binary_sensor.template_udm_internet'],
                    upgradable = states['binary_sensor.template_udm_upgradable'];
                  if (internet && upgradable) {
                    return upgradable.state === 'on'
                      ? 1
                      : internet.state === 'off';
                  }
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:raspberry-pi"></ha-icon> RPi
            tap_action:
              !include popup/footer/rpi.yaml
            variables:
              notify: >
                [[[
                  let ping = states['binary_sensor.rpi_ping'];
                  if (ping) {
                    return ping.state === 'off';
                  }
                ]]]
            template: footer
