automation:
    - alias: 'Motion Detected at Night - Turn On Light'
      trigger:
          - platform: state
            entity_id: binary_sensor.terrace_back_person_occupancy
            to: 'detected'
          - platform: state
            entity_id: binary_sensor.terrace_side_person_occupancy
            to: 'detected'
      condition:
          - condition: state
            entity_id: sun.sun
            state: 'below_horizon' # Trigger the automation when the sun is below the horizon (nighttime)
      action:
          - service: script.turn_on_light

    - alias: 'Turn off light after X minutes'
      trigger:
          - platform: state
            entity_id: light.terrasse # Replace with your light entity
            to: 'on'
            for:
                minutes: 5 # Adjust as needed (X minutes)
      action:
          - service: light.turn_off
            entity_id: light.terrasse # Replace with your light entity
